name: Deploy to AWS S3

on:
  push:
    branches:
      - main # Change to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.15.0 # Set your desired Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Deploy to AWS S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete --follow-symlinks
    
      env:
        AWS_REGION: us-west-1 # Set your desired AWS region
        AWS_S3_BUCKET: referdental # Replace with your bucket's name
        SOURCE_DIR: build
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

